source 'https://rubygems.org'

gem 'rails', '4.1'
gem 'sqlite3'
gem 'sass-rails', '~> 4.0.0'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.0.0'
gem 'jquery-rails'
gem 'turbolinks'
gem 'jbuilder', '~> 1.2'

group :development, :test do
  gem "mocha", require: false
  gem 'rspec-rails', '3.0.0.beta2'
  gem 'capybara'
end

group :test do
  #gem "minitest-rails-capybara"
  gem 'm'
end
gem 'bcrypt-ruby', '~> 3.0.0'

group :doc do
  gem 'sdoc', require: false
end
